spring.application.name=storeapp
server.port=8080

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true


# spring.datasource.url=jdbc:mysql://db.azaken.com:4000/test?sslMode=VERIFY_IDENTITY&useSSL=true&enabledTLSProtocols=TLSv1.2,TLSv1.3
# spring.datasource.username=2FGj73hAxruaqyU.root
# spring.datasource.password=YourPassword


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=default_long_secret_key_only_for_dev	
app.jwt.expirationMs=86400000

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs